[package]
name = "lnpbp"
version = "0.1.0-alpha.1"
license = "MIT"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Library implementing LNPBPs specifications & standards"
repository = "https://github.com/lnp-bp/rust-lnpbp"
homepage = "https://github.com/lnp-bp"
keywords = ["bitcoin", "lightning", "lnp/bp", "layer-3", "cryptography"]
readme = "README.md"
edition = "2018"

[lib]
name = "lnpbp"
path = "src/lib.rs"

[dependencies]
bitcoin = { git = "https://github.com/lnp-bp/rust-bitcoin", branch = "staging", features = [ "use-serde" ] }
lightning = { git = "https://github.com/lnp-bp/rust-lightning", branch = "staging", optional = true }
lightning-net-tokio = { git = "https://github.com/lnp-bp/rust-lightning", branch = "staging", optional = true }
miniscript = { git = "https://github.com/lnp-bp/rust-miniscript", branch = "staging" }
grin_secp256k1zkp = { git = "https://github.com/lnp-bp/rust-secp256k1-zkp", branch = "stable" }
# bitcoin = { version = "0.23.0", features = [ "use-serde" ] }
rand = "0.5" # Required by grin_secp256k1zkp
derive_wrapper = "0.1.3"
num-integer = "0.1.42"
num-traits = "0.2.11"
num-derive = "0.3.0"
tokio = { version = "0.2.16", features = ["tcp"], optional = true }
hex = { version = "=0.3.2" }
torut = { version = "0.1.1", optional = true }

[features]
default = []
all = ["use-tor", "use-lightning", "use-tokio"]
use-tor = ["torut"]
use-lightning = ["lightning"]
use-tokio = ["use-lightning", "tokio/tcp", "lightning-net-tokio"]
